import './js/fetch';
import './js/library-buttons';
import './js/markupFromStorage';
import './js/watchedRender';
import './js/modal-footer';
import './js/advertisingPremium';
import './js/theme-darck-light';
import './js/trailer';
import './js/preloader';
